server:
  port: 8000

msa:
  product-service:
    url: localhost:8001
  user-service:
    url: localhost:8002


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
      max-lifetime: 30000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true